version: "3.9"

services:
  admin_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_app_prod
    working_dir: /var/www
    volumes:
      - .:/var/www
      - admin_vendor_prod:/var/www/vendor
    env_file:
      - .env.prod
    environment:
      APP_ENV: production
      DB_HOST: db
      DB_CONNECTION: pgsql
      DB_PORT: 5432
      DB_DATABASE: goouty
      DB_USERNAME: admin
      DB_PASSWORD: Admin123

  admin_web:
    image: nginx:alpine
    container_name: admin_web_prod
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - admin_app

volumes:
  admin_vendor_prod:

networks:
  default:
    external: true
    name: goouty-network